scheduler:
  image:
    tag: "0.19.2"

worker:
  image:
    tag: "0.19.2"
  replicas: 4
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray scipy matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: s3fs dask-ml librosa --upgrade

# We want to keep the same packages on the worker and jupyter environments
jupyter:
  enabled: true
  image:
    tag: "0.19.2"
  env:
    - name: EXTRA_CONDA_PACKAGES
      value: numba xarray scipy matplotlib -c conda-forge
    - name: EXTRA_PIP_PACKAGES
      value: s3fs dask-ml librosa --upgrade
